#!/bin/bash

########################################################################
#                                                                      #
# copy-file                                                            #
#                                                                      #
# Copyright (C) 2020 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
source_path=${1}
target_path=${2}

# echo "program..................... $program"
# echo "number of arguments......... $number_arguments"
# echo "source path................. ${source_path}."
# echo "target path................. ${target_path}."

########################################################################
# Command
########################################################################

rsync --archive --info=progress2 "${source_path}" "${target_path}"
