#!/bin/bash

########################################################################
#                                                                      #
# extract-root                                                         #
#                                                                      #
# Copyright (C) 2020 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

# Extract the root file system for Cubic.

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
target_file_path=${1}
source_file_path=${2}
has_error_option=${3}

# echo "program..................... ${program}"
# echo "number of arguments......... ${number_arguments}"
# echo "target file path............ ${target_file_path}"
# echo "source file path............ ${source_file_path}"
# echo "has error option............ ${has_error_option}"

########################################################################
# Command
########################################################################

# Exit Status Codes
#
# https://manpages.ubuntu.com/manpages/focal/man1/unsquashfs.1.html
# https://manpages.ubuntu.com/manpages/jammy/man1/unsquashfs.1.html
# https://manpages.ubuntu.com/manpages/noble/man1/unsquashfs.1.html
# https://manpages.ubuntu.com/manpages/plucky/man1/unsquashfs.1.html
#
# 0 The filesystem listed or extracted OK.
# 1 FATAL errors occurred, e.g. filesystem corruption, I/O errors.
#   Unsquashfs did not continue and aborted.
# 2 Non-fatal errors occurred, e.g. no support for XATTRs, Symbolic
#   links in output filesystem or couldn't write permissions to
#   output filesystem. Unsquashfs continued and did not abort.
# See -ignore-errors, -strict-errors and -no-exit-code options for
# how they affect the exit status.
#
# These options are available in squashfs version 4.5 and above.
# -ignore-errors = treat errors writing files to output as non-fatal
# -strict-errors = treat all errors as fatal
# -no-exit-code = do not set exit code (to nonzero) on non-fatal errors
#
# The following versions of Ubuntu and squashfs do not support these options.
#
# Ubuntu Version                        Squashfs Version
# ----------------------------------    ----------------
# Ubuntu 20.04.6 LTS Focal Fossa        4.4
# Ubuntu 20.10 Groovy Gorilla           4.4
# Ubuntu 21.04 Hirsute Hippo            4.4
# Ubuntu 21.10 Impish Indri             4.4
#
# The following versions of Ubuntu and squashfs support these options:
#
# Ubuntu Version                        Squashfs Version
# ----------------------------------    ----------------
# Ubuntu 22.04.5 LTS Jammy Jellyfish    4.5
# Ubuntu 22.10 Kinetic Kudu             4.5.1
# Ubuntu 23.04 Lunar Lobster            4.5.1
# Ubuntu 23.10 Mantic Minotaur          4.6.1
# Ubuntu 24.04.2 LTS Noble Numbat       4.6.1
# Ubuntu 24.10 Oracular Oriole          4.6.1
# Ubuntu 25.04 Plucky Puffin            4.6.1
#
# Use echo $? to check the error status.
# http://www.tldp.org/LDP/abs/html/exitcodes.html
#
# The following fatal error occurs when extracting Ubuntu 25.04:
# FATAL ERROR: create_inode: failed to create hardlink, because File exists

if [[ ${has_error_option} ]]; then
    # Ubuntu 22.04.5 LTS Jammy Jellyfish +
    # Unsquashfs version 4.5+
    unsquashfs -force -no-exit-code -ignore-errors -dest "${target_file_path}" "${source_file_path}"
else
    # Ubuntu 20.04 LTS Focal Fossa thru Ubuntu 21.10 Impish Indri
    # Unsquashfs version 4.4
    unsquashfs -force -dest "${target_file_path}" "${source_file_path}"
    # # Use echo $? to check the error status.
    # # http://www.tldp.org/LDP/abs/html/exitcodes.html
    # exit_code=$?
    # if [[ $exit_code -eq 1 ]]; then
    #     # Ignore fatal errors.
    #     # WARNING: The extract process may not have completed successfully due
    #     # to the error.
    #     echo "Ignoring fatal errors."
    #     exit_code=0
    # elif [[ $exit_code -eq 2 ]]; then
    #     # Ignore non-fatal errors.
    #     # WARNING: The extract process may not have completed successfully due
    #     # to the error.
    #     echo "Ignoring non-fatal errors."
    #     exit_code=0
    # fi
    # exit $exit_code
fi

