#!/bin/bash

########################################################################
#                                                                      #
# merge-directory                                                      #
#                                                                      #
# Copyright (C) 2025 PJ Singh <psingh.cubic@gmail.com>                 #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
# This file is part of Cubic - Custom Ubuntu ISO Creator.              #
#                                                                      #
# Cubic is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Cubic is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Cubic. If not, see <http://www.gnu.org/licenses/>.        #
#                                                                      #
########################################################################

# Merge a source directory into a target directory for Cubic.

########################################################################
# Arguments
########################################################################

program=${0}
number_arguments=${#}
source_directory=${1}
target_directory=${2}

# echo "program..................... ${program}"
# echo "number of arguments......... ${number_arguments}"
# echo "source directory............ ${source_directory}"
# echo "target directory............ ${target_directory}"

########################################################################
# Command
########################################################################

# Sync contents from source to target, preserving devices and special files,
# update files in place, and remove source regular files after transfer.
rsync --archive --devices --specials --inplace --remove-source-files --info=progress2 "${source_directory}/" "${target_directory}"

# Flush all pending file system writes.
sync

# Rsync does not remove block, character, or network special files. Therefore
# delete all files that are not regular files, directories, or symbolic links.
find "${source_directory}" ! \( -type f -o -type d -o -type l \) -exec rm -f {} +

# Next, delete all empty directories. Directories that contain regular files
# (that were not copied) will not be empty.
find "${source_directory}" -type d -empty -delete

# Check if the source directory is empty.
if [ -d "${source_directory}" ]; then
    # If the source directory is not empty, the copy was unsuccessful.
    echo "Error. The directory ${source_directory} is not empty."
    exit 1
fi
