.\" Manual page for cubic.
.\" Copyright (C) 2015, 2020 PJ Singh <psingh.cubic@gmail.com>

.TH cubic 1 "March 30, 2018" "" "Cubic"

.SH NAME
\fBcubic\fR - Custom Ubuntu ISO Creator

.SH SYNOPSIS
.B cubic

.SH DESCRIPTION
Cubic is a wizard application to create a customized bootable Ubuntu Live CD ISO
image.
.PP
Cubic features an integrated command line chroot environment to make the
customizations and permits effortless navigation, backward and forward, through
the ISO generation steps. You can create new customization projects or modify
existing projects. Important parameters are automatically populated with
intelligent defaults to simplify the customization process.
.PP
See <https://launchpad.net/cubic> for more information.

.SH OPTIONS
No options are required to run \fBcubic\fR.

.SH NOTES
Cubic is a graphical user interface application and should be run using the
application launcher.
.PP
To run Cubic from the command line, use the \fBcubic\fR command; this executable
is located in the /usr/bin directory and should be available in your path.
Cubic may not be run as a privileged user. Instead, run the \fBcubic\fR command
using an account with sudo (superuser) membership, and you will be prompted for
the superuser password.

.SH BUGS
Report bugs to <https://bugs.launchpad.net/cubic>

.SH AUTHOR
PJ Singh <psingh.cubic@gmail.com>
